### ISSUE TITLE
Not on C1 ARM server?

### ISSUE THREAD

**Issue by Bacto** [scaleway-community/scaleway-mattermost#5]
Hi guys,

Unfortunately Mattermost is not available on C1 ARM server.
Is it an omission and do you have plans to add it to C1?

Thanks,
Adrien

**Comment by MoonCactus** [comment]
Actually, I find no image of mattermost anymore, and whichever the kind of server... Is the support of mattermost dropped ?

**Comment by Hatrix42** [comment]
Working on it, you can expect a release today if everything goes well :)

**Comment by Hatrix42** [comment]
The Mattermost image has been updated and can now be used on x86_64 servers on both PAR1 and AMS1.
Mattermost developers do not provide binaries for ARM though and thus must be compiled. Do you still need ARM support @Bacto ?

**Comment by Bacto** [comment]
Nop I don't need it anymore, thanks :)
